# Java
## ASTM-1
### BEST -> rename its log to java_astm1_best and move it inside results directories
python3 train.py --data_path ../data/so_java.txt --post_tags_path ../data/so_java_question_tags.pkl --post_score_path ../data/so_java_post_score.pkl --result_path skj_ml_232 --train_part 1.0 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 100 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM1
### parameter sensitivity
python3 train.py --data_path ../data/so_java.txt --post_tags_path ../data/so_java_question_tags.pkl --post_score_path ../data/so_java_post_score.pkl --result_path skj_ml_235 --train_part 1.0 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 50 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM1
python3 train.py --data_path ../data/so_java.txt --post_tags_path ../data/so_java_question_tags.pkl --post_score_path ../data/so_java_post_score.pkl --result_path skj_ml_241 --train_part 1.0 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 150 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM1
python3 train.py --data_path ../data/so_java.txt --post_tags_path ../data/so_java_question_tags.pkl --post_score_path ../data/so_java_post_score.pkl --result_path skj_ml_247 --train_part 1.0 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 200 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM1

python3 train.py --data_path ../data/so_java.txt --post_tags_path ../data/so_java_question_tags.pkl --post_score_path ../data/so_java_post_score.pkl --result_path skj_ml_230 --train_part 0.5 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 100 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM1
python3 train.py --data_path ../data/so_java.txt --post_tags_path ../data/so_java_question_tags.pkl --post_score_path ../data/so_java_post_score.pkl --result_path skj_ml_231 --train_part 0.75 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 100 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM1

## ASTM-2
### BEST -> rename its log to java_astm2_best and move it inside results directories
python3 train.py --data_path ../data/so_java.txt --post_tags_path ../data/so_java_question_tags.pkl --post_score_path ../data/so_java_post_score.pkl --result_path skj_ml_225 --train_part 0.75 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 100 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM2
### parameter sensitivity
python3 train.py --data_path ../data/so_java.txt --post_tags_path ../data/so_java_question_tags.pkl --post_score_path ../data/so_java_post_score.pkl --result_path skj_ml_237 --train_part 0.75 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 50 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM2
python3 train.py --data_path ../data/so_java.txt --post_tags_path ../data/so_java_question_tags.pkl --post_score_path ../data/so_java_post_score.pkl --result_path skj_ml_243 --train_part 0.75 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 150 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM2
python3 train.py --data_path ../data/so_java.txt --post_tags_path ../data/so_java_question_tags.pkl --post_score_path ../data/so_java_post_score.pkl --result_path skj_ml_249 --train_part 0.75 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 200 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM2

python3 train.py --data_path ../data/so_java.txt --post_tags_path ../data/so_java_question_tags.pkl --post_score_path ../data/so_java_post_score.pkl --result_path skj_ml_224 --train_part 1.0 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 100 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM2
python3 train.py --data_path ../data/so_java.txt --post_tags_path ../data/so_java_question_tags.pkl --post_score_path ../data/so_java_post_score.pkl --result_path skj_ml_226 --train_part 0.5 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 100 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM2

# PHP
## ASTM-1
### BEST -> rename its log to php_astm1_best and move it inside results directories
python3 train.py --tag php --data_path ../data/so_php.txt --post_tags_path ../data/so_php_question_tags.pkl --post_score_path ../data/so_php_post_score.pkl --result_path skp_ml_284 --train_part 1.0 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 100 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM1
### parameter sensitivity
python3 train.py --tag php --data_path ../data/so_php.txt --post_tags_path ../data/so_php_question_tags.pkl --post_score_path ../data/so_php_post_score.pkl --result_path skp_ml_278 --train_part 1.0 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 50 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM1
python3 train.py --tag php --data_path ../data/so_php.txt --post_tags_path ../data/so_php_question_tags.pkl --post_score_path ../data/so_php_post_score.pkl --result_path skp_ml_302 --train_part 1.0 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 150 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM1
python3 train.py --tag php --data_path ../data/so_php.txt --post_tags_path ../data/so_php_question_tags.pkl --post_score_path ../data/so_php_post_score.pkl --result_path skp_ml_308 --train_part 1.0 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 200 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM1

python3 train.py --tag php --data_path ../data/so_php.txt --post_tags_path ../data/so_php_question_tags.pkl --post_score_path ../data/so_php_post_score.pkl --result_path skp_ml_288 --train_part 0.5 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 100 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM1
python3 train.py --tag php --data_path ../data/so_php.txt --post_tags_path ../data/so_php_question_tags.pkl --post_score_path ../data/so_php_post_score.pkl --result_path skp_ml_286 --train_part 0.75 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 100 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM1

## ASTM-2
### BEST -> rename its log to php_astm2_best and move it inside results directories
python3 train.py --tag php --data_path ../data/so_php.txt --post_tags_path ../data/so_php_question_tags.pkl --post_score_path ../data/so_php_post_score.pkl --result_path skp_ml_267 --train_part 1.0 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 50 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM2
### parameter sensitivity
python3 train.py --tag php --data_path ../data/so_php.txt --post_tags_path ../data/so_php_question_tags.pkl --post_score_path ../data/so_php_post_score.pkl --result_path skp_ml_273 --train_part 1.0 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 100 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM2
python3 train.py --tag php --data_path ../data/so_php.txt --post_tags_path ../data/so_php_question_tags.pkl --post_score_path ../data/so_php_post_score.pkl --result_path skp_ml_291 --train_part 1.0 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 150 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM2
python3 train.py --tag php --data_path ../data/so_php.txt --post_tags_path ../data/so_php_question_tags.pkl --post_score_path ../data/so_php_post_score.pkl --result_path skp_ml_297 --train_part 1.0 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 200 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM2

python3 train.py --tag php --data_path ../data/so_php.txt --post_tags_path ../data/so_php_question_tags.pkl --post_score_path ../data/so_php_post_score.pkl --result_path skp_ml_271 --train_part 0.5 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 50 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM2
python3 train.py --tag php --data_path ../data/so_php.txt --post_tags_path ../data/so_php_question_tags.pkl --post_score_path ../data/so_php_post_score.pkl --result_path skp_ml_269 --train_part 0.75 --post_type question --embedding_type lda --num_words 5000 --word_vector_dim 50 --max_sentence_len 240 --epochs 10 --batch_size 32 --validation_split 0.1 --model_name ASTM2
